#!/bin/sh
cd /tmp || exit

# TODO Implement OS logic to select the correct initialziation script
#
wget https://raw.githubusercontent.com/blacktower/devops/master/GoogleCloud/debian/initialize.sh
chmod +x initialize.sh
./initialize.sh > initialize.log