#!/bin/sh
cd /tmp || exit

# TODO Implement OS logic to select the correct initialziation script
# if (AmazonLinux) then
# wget https://raw.githubusercontent.com/blacktower/devops/master/AmazonAWS/Amazon/initialize.sh
# elseif (ubuntu) then
# wget https://raw.githubusercontent.com/blacktower/devops/master/AmazonAWS/Ubuntu/initialize.sh
# elseif (debian) then
# wget https://raw.githubusercontent.com/blacktower/devops/master/GoogleCloud/debian/initialize.sh
chmod +x initialize.sh
./initialize.sh > initialize.log